### ISSUE TITLE
Can't find a list of components

### ISSUE THREAD

**Issue by iWhacko** [RyscCorp/magspoof_r3#4]
Hi, I was looking at the schematics and couldn't find a list of components. Are they the same as Samy's Magspoof? or is there an alternate list?

**Comment by DrBabbage** [comment]
You can find it in the CAD files. Here is the stuff I bought at digikey.

sw2 P15961SCT-ND
sw1 401-1999-1-ND
R1 CR0603-JW-331ELFCT-ND
LED1 475-1410-1-ND
u1 TC4424AVOA713CT-ND
IC1 ATTINY85-20SU-ND
C3 399-1100-1-ND
C2 478-3080-1-ND
C1 478-3080-1-ND
BAT1 36-3002-ND

**Comment by iWhacko** [comment]
Thank you DrBabbage. I must've done something wrong because I couldn't find it myself. But this helps a lot.
